language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - boost-latest
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
    # Latest GCC for C++14
    - gcc-5
    - g++-5
    # Boost
    - libboost-system1.55-dev 
    - libboost-filesystem1.55-dev 
    - libboost-program-options1.55-dev
    # Protobuf
    - libprotobuf-dev
    - protobuf-compiler

matrix:
  allow_failures:
    - compiler: clang
    - os: osx

before_install:
  # Prepare compiler
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

script:
 # Build and run the tests
 # - rm -rf build/ && mkdir build/ && cd build/ && cmake .. && cmake --build . && ctest
 - rm -rf build/ && mkdir build/ && cd build/ && cmake .. && make VERBEROSE=1  && ctest

notifications:
  email: false

sudo: false

cache:
  - apt

