language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - LIBSTDC_VERSION=5
    - CLANG_VERSION=3.6

matrix:
  allow_failures:
    - compiler: clang
    - os: osx

before_install:
  # Setup cmake
  - sh scripts/install-cmake.sh

  # Prepare compilers
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

  # Debug information
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then lsb_release -a; fi
  - uname -a
  - $CC --version
  - $CXX --version

script:
 # Run cmake
 - rm -rf build/ && mkdir build/ && cd build/ && cmake ..

after_success:
 # Build and run tests
 - make && make test

notifications:
  email: false

sudo: required

cache:
  - apt
